### ISSUE TITLE
[Build Fails]:  Cannot find module 'kcd-scripts/babel' 

### ISSUE THREAD

**Issue by chandanrjit** [kentcdodds/kcd-scripts#125]
I'm trying to use this module to replace babel in the below project but getting errors. Any help is appreciated.

Git repo : [https://github.com/chandanrjit/react-webpack-boilerplate](https://github.com/chandanrjit/react-webpack-boilerplate)

usage:

`{"presets": ["kcd-scripts/babel"]}`

```
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'kcd-scripts/babel' from 'C:\workspace\code\research\react-webpack-boilerplate'
    at Function.resolveSync [as sync] (C:\workspace\code\research\react-webpack-boilerplate\node_modules\resolve\lib\sync.js:81:15)    at resolveStandardizedName (C:\workspace\code\research\react-webpack-boilerplate\node_modules\@babel\core\lib\config\files\plugins.js:101:31)

```

**Comment by kentcdodds** [comment]
Try:

```
{"presets": ["./node_modules/kcd-scripts/babel"]}
```

**Comment by chandanrjit** [comment]
It worked . Thanks Kent for quick reply.
