### ISSUE TITLE
Environment key "jest/globals" is unknown

### ISSUE THREAD

**Issue by jorgemoya** [kentcdodds/kcd-scripts#185]
- `kcd-scripts` version: 7.5.3
- `node` version: 10.22.0
- `npm` (or `yarn`) version: yarn 1.22.5

Relevant code or config

```javascript
  "eslintConfig": {
    "extends": "./node_modules/kcd-scripts/eslint.js",
     ...
  },
  "husky": {
    "hooks": {
      "pre-commit": "kcd-scripts pre-commit"
    }
  },
```

What you did:
Trying to make a commit on the `Downshift` library I get an error when `kcd-scripts lint` is running.

What happened:

```
❯ git commit -m "fix: test"
husky > pre-commit (node v10.22.0)
✔ Preparing...
⚠ Running tasks...
  ↓ No staged files match README.md [SKIPPED]
  ❯ kcd-scripts lint [FAILED]
    ✔ kcd-scripts format
    ✖ kcd-scripts lint [FAILED]
    ◼ kcd-scripts test --findRelatedTests
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ kcd-scripts lint:

Oops! Something went wrong! :(

ESLint: 7.15.0

Error: package.json » ./node_modules/kcd-scripts/eslint.js » /Users/jorge.moya/dev/downshift/node_modules/kcd-scripts/node_modules/eslint-config-kentcdodds/jest.js:
        Environment key "jest/globals" is unknown

    at Object.keys.forEach.id (/Users/jorge.moya/dev/downshift/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:173:23)
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (/Users/jorge.moya/dev/downshift/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:167:34)
    at ConfigValidator.validateConfigArray (/Users/jorge.moya/dev/downshift/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:317:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/jorge.moya/dev/downshift/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/jorge.moya/dev/downshift/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at FileEnumerator._iterateFilesWithFile (/Users/jorge.moya/dev/downshift/node_modules/kcd-scripts/node_modules/eslint/lib/cli-engine/file-enumerator.js:365:43)
    at FileEnumerator._iterateFiles (/Users/jorge.moya/dev/downshift/node_modules/kcd-scripts/node_modules/eslint/lib/cli-engine/file-enumerator.js:346:25)
    at FileEnumerator.iterateFiles (/Users/jorge.moya/dev/downshift/node_modules/kcd-scripts/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:59)
    at iterateFiles.next (<anonymous>)
husky > pre-commit hook failed (add --no-verify to bypass)
```

Reproduction repository: https://github.com/downshift-js/downshift/

I wasn't sure if it was best to report this issue here on in `eslint-config-kentcdodds`. Let me know if I should move the issue somewhere else, thank you.

**Comment by jorgemoya** [comment]
Noticed this was reported before.
