### ISSUE TITLE
@babel/runtime error

### ISSUE THREAD

**Issue by benmonro** [kentcdodds/kcd-scripts#86]
- `kcd-scripts` version: 1.2.1
- `node` version: 10.11.0
- `npm` (or `yarn`) version: npm 6.9.0

Relevant code or config

```json
  "scripts": {
    "test": "kcd-scripts test --config=jest.config.js"
  },
```

What you did:
`npm run test`
What happened:
```
Error: You should add @babel/runtime as dependency to your package. It will allow reusing "babel helpers" from node_modules rather than bundling their copies into your files.
    at Object.<anonymous> (/Users/bmonro001/Code/react-svelte/node_modules/kcd-scripts/dist/config/babelrc.js:33:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/bmonro001/Code/react-svelte/node_modules/kcd-scripts/dist/config/index.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

Reproduction repository:
https://github.com/benmonro/react-svelte/tree/bug/kcd-script-error

Problem description:
why do i need to install @babel/runtime as a (non dev) dependency just to run tests?
Suggested solution:
have kcd-scripts not require that dep.

**Comment by kentcdodds** [comment]
You may not need it for tests, but you will for the build.

**Comment by benmonro** [comment]
what if i'm not using it for the build, but just for tests?

**Comment by kentcdodds** [comment]
You can make a PR into ignore this warning for tests 👍

**Comment by benmonro** [comment]
You and your whole "getting the community involved" thing!  ok will do. 😜
