### ISSUE TITLE
Environment key "jest/globals" is unknown

### ISSUE THREAD

**Issue by JeffBaumgardt** [kentcdodds/kcd-scripts#91]
- `kcd-scripts` version: 1.5.2
- `node` version: 12.6.0
- `npm` (or `yarn`) version: Yarn 1.12.1

Relevant code or config

I fave the following script in my package.json ```"lint": "kcd-scripts lint --config .eslintrc.js --ignore-path .eslintignore"```

My eslintrc.js file contains:
```javascript
module.exports = {
	extends: './node_modules/kcd-scripts/eslint.js',
	rules: {
		'import/extensions': [
			'error',
			{
				json: 'always',
				js: 'never',
				css: 'off',
				jpg: 'always',
				png: 'always',
				JPG: 'always',
			},
		],
		'react/prop-types': 'warn',
	},
}
```

What you did:
Ran script `yarn run lint`

What happened:
The result is in a eslint config validator error `Environment key "jest/globals" is unknown`

```cli
Jeffs-Air:SpacePoints jeffbaumgardt$ yarn run lint
yarn run v1.12.1
$ kcd-scripts lint --config .eslintrc.js --ignore-path .eslintignore
Error: .eslintrc.js » ./node_modules/kcd-scripts/eslint.js » /Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint-config-kentcdodds/jest.js:
        Environment key "jest/globals" is unknown

    at /Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint/lib/shared/config-validator.js:169:19
    at Array.forEach (<anonymous>)
    at validateEnvironment (/Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint/lib/shared/config-validator.js:163:30)
    at validateConfigArray (/Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint/lib/shared/config-validator.js:334:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:392:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:248:21)
    at FileEnumerator._iterateFilesRecursive (/Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint/lib/cli-engine/file-enumerator.js:400:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/jeffbaumgardt/Node/SpacePoints/node_modules/kcd-scripts/node_modules/eslint/lib/cli-engine/file-enumerator.js:254:49)
    at iterateFiles.next (<anonymous>)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Reproduction repository:
https://github.com/JeffBaumgardt/testingCRA-KCDScripts
This is a fresh install of CRA and kcd-scripts only files added are the .eslintignore and .eslintrc.js files. Added lint script to package.json

Problem description:
The config validator for eslint is complaining about the env flag for jest/globals. I'm not sure why as this is a valid flag per the `eslint-plugin-jest` plugin. I've looked around and have not been able to find any information pertaining to this issue. On eslint-plugin-jest, eslint, or eslint-config-kentcdodds.

If this issue is better placed in the eslint-config-kentcdodds repo I will be happy to add it there.

Suggested solution:
I don't have any good ideas at the moment.

**Comment by kentcdodds** [comment]
Hi @JeffBaumgardt,

I'm sorry, but I don't have the bandwidth to provide support on this project :-(

That's applies to all projects that have my name in them (like my eslint config and my oss generator). I maintain these for myself. Sorry to be unhelpful here :-/
